### ISSUE TITLE
Great repo

### ISSUE THREAD

**Issue by Hangwei12358** [SolaceSJ/Awsome_Human_Activity_Recognition#1]
Hi, 

Thanks for maintaining a repo on human activity recognition. I also work on this task and have several papers that may seem interesting to you. I have worked on supervised learning/semi-supervised/weakly-supervised learning as well as transfer learning on human activity recognition. If you want to try out the codes, please refer to [the website](http://hangwei12358.github.io/Publications/). Thanks!

**Comment by Jie-su** [comment]
Hi,

Thanks for your comment! I will add ur paper to the repo, excellent work! I will keep maintaining the repo for har task. Hopefully, I can give more clear structure and layout of the content.

Many thanks for that.

Jie
